server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://spark01:3306/reserver_system?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: pingcai
    password: 960064@pingcai
#  devtools: # 热部署
  #    livereload:
  #      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    static-path-pattern: classpath:/static/
mybatis-plus:
  type-aliases-package: com.yanzhen.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yanzhen/dao/*.xml

